### ISSUE TITLE
How do you configure the path?

### ISSUE THREAD

**Issue by pupeno** [AndreyNikiforov/vault2git#1]
It's not very clear in the documentation how to configure the paths. Can you show an example? What paths? why more than one?

**Comment by AndreyNikiforov** [comment]
Convertor.Paths in .config is semicolon separated list of path-branch matches. if in vault repo you have trunk under $/myTrunk, then Convertor.Paths will be "@/myTrunk~master".

vault2git cannot create branches yet, so after processing trunk, you'll have to create branches in git manually, update Convertor.Paths, and then run vault2git again. 

Let's say you have "$/branches/abcFeature" branch. You will create new branch in git (let's say it will be "defFeature", just to show that name of the branch in git can be different from vault), and update Convertor.Paths to "@/myTrunk~master;$/branches/abcFeature~defFeature"

**Comment by pupeno** [comment]
Where do you specify the address of the Vault server itself, like http://....

**Comment by AndreyNikiforov** [comment]
you set it in .config file in Vault.Server key. It should be just server name (without http://). user and password are set in the .config as well.
