### ISSUE TITLE
How does vault2git handle shared files?

### ISSUE THREAD

**Issue by jbuedel** [AndreyNikiforov/vault2git#18]
"Shared" as in the Vault feature explained here http://download.sourcegear.com/misc/vault/help/client/share.html.

We make heavy use of the share feature, but we also use git on a number of other projects and rather like it. We're discussing how we might work with these shared files should we move to git.

**Comment by AndreyNikiforov** [comment]
@jbuedel I did not test vault2git with Share feature. From description on sourcegear site it seems that shared files will appear in two places and git will pick them both separately. Give it a try and let me know how it worked for you.

**Comment by jbuedel** [comment]
Thanks. We'll check it out.
