### ISSUE TITLE
Unable to run exe file

### ISSUE THREAD

**Issue by rajasekaran07** [AndreyNikiforov/vault2git#19]
Hi ..

I replaced my vault client api dll and recompiled this package and created exe file. When I run my exe file I got below error. Any Idea on this and how to fix this. I tried with admin account but same alert window came.

![image](https://user-images.githubusercontent.com/19193992/28416810-29ad74a4-6d73-11e7-8409-0904658f2590.png)

**Comment by AndreyNikiforov** [comment]
@rajasekaran07  I can suggest running with debugger to identify what operation causes exception. My guess is that access to vault is somehow limited. That assumes that you have Admin rights on your PC.

**Comment by rajasekaran07** [comment]
I am the owner of my system. I tried with run as administrator also. PFB error i am getting.

![image](https://user-images.githubusercontent.com/19193992/28450168-40c1644e-6e03-11e7-9bbe-4d3147258c50.png)

**Comment by AndreyNikiforov** [comment]
@rajasekaran07 Fails at Vault login.

The error suggests that Vault dlls are trying to access settings.xml file and fail. Try running Visual Studio as Administrator (right click on VS icon and select 'Run as Administrator') and repeat the same test.

**Comment by rajasekaran07** [comment]
@AndreyNikiforov 

I tried with administrator but, getting same error.

![image](https://user-images.githubusercontent.com/19193992/28509299-ee54e768-705e-11e7-9081-1b1257148b85.png)

By the way when I checked in that particular path "C:\Users\URADHR1\AppData\Local\Sourcegear\Client\settings.xml" I am not seeing settings.xml file. Is there any way to generate settings.xml file.

Regards,
Raja

**Comment by AndreyNikiforov** [comment]
@rajasekaran07 I am no longer keeping track of Vault client versions, dependencies, and installation peculiarities. Error suggests that settings.xml file is expected by Vault client dlls, but it is not available. You can post detailed version of the Vault client/dlls you are using in the hope that somebody else can help you.

You can try reaching Vault forums and search for this particular problem.

You can also write a small app just to establish Vault connection. That will isolate Vault connectivity from vautl2git conversion functionality and will help you troubleshooting (and communicate with vault community).
