### ISSUE TITLE
Intermittent Exception in vaultGet()

### ISSUE THREAD

**Issue by crossan007** [AndreyNikiforov/vault2git#22]
Occasionally (usually after a few hundred/thousand) commits, an exception may arise:

```
the working folder state information for is incompatible with this version of vault
```

This might be caused by stale client-side cache:
https://elegantcode.com/2009/07/01/vault-and-cruisecontrolnet-error-working-folder-state-problem/

Other:
* https://support.sourcegear.com/viewtopic.php?f=13&t=11513
* https://support.sourcegear.com/viewtopic.php?f=5&t=15445

**Comment by AndreyNikiforov** [comment]
@crossan007 vault2git was written resilient to crashes: it stores vault commit references in git commit messages and that allows conversion to be started where it was left off. It is a work around for the problem you mentioned, not a solution, but in the current state of affairs it is the best I can offer: I am not using vault after I wrote this code and successfully converted to git 7 years ago. I hope that with a small number of hiccups and restarts you will convert your repo and move on. Good luck!

**Comment by crossan007** [comment]
Thanks!   

I noticed that it will resume from the previous commit.

I made some changes that will cause the offending "commit" to clear the cache and resume automagically - I've got a Vault repo with ~500,000 history items and I don't want to baby sit the process ;-)
 
I'll submit a PR on Monday.
