### ISSUE TITLE
Is SSL supported?

### ISSUE THREAD

**Issue by jocull** [AndreyNikiforov/vault2git#3]
I'm looking into migrating our repo with this tool. I've given it a little work and dug into the source, but I can't seem to get SSL working. Things seem to be getting tied up inside of `vaultLogin()` in `Vault2Git.Lib.Processor` just after `ServerOperations.Login();` is called.

Is the a specific setting that needs to be changed to enable SSL? I tried changing the URL in this line...

```
ServerOperations.client.LoginOptions.URL = string.Format("http://{0}/VaultService", this.VaultServer);
```

...to this, thinking that the HTTPS may trigger the SSL. Our server is also on port 79, which may be throwing it off further.

```
ServerOperations.client.LoginOptions.URL = string.Format("https://{0}/VaultService", this.VaultServer);
```

**Comment by jocull** [comment]
Looking into this further, I believe HTTPS is correct...

The error returned is `The server uses a protocol that is not supported by this client.`, so I think our Vault server being 3.1.9.3798 is conflicting with the default vault API libraries you provided. I'm looking at downgrading them, but the differences are pretty severe. Most importantly `VaultClientIntegrationLib` doesn't seem to even exist before 4.0.

**Comment by AndreyNikiforov** [comment]
As far as I know Vault libs are set for specific server version. For each version of the server product you have to have its own version of client lib. I think API changes between them as well. I worked with 4.x version only and don't know what Vault APIs existed before that version (or after for that matter).

If you are committed to git, you may explore an option of upgrading server. If you are just researching git, I cannot suggest anything other than changing code for your version of Vault lib (if it is even available).

**Comment by jocull** [comment]
Thanks for the advice. We're actually looking at moving to Kiln (Mercurial) since we're largely Windows based and like some of the other perks. I was trying to use Git as the pass-thru on the way to full migration from Vault to Mercurial, since I couldn't find any Vault to Mercurial tools.
