### ISSUE TITLE
Fortress

### ISSUE THREAD

**Issue by rodneyjwoodruff** [AndreyNikiforov/vault2git#6]
Hi,

It appears that this doesn't work with Vault Professional. Do you have initial ideas about making this work with the Fortress Client? I might be able to help make it work but need a little direction. You can see the stack trace in this ticket in the sourceforge forum at this ticket.

http://kb.sourcegear.com/FortressHelp/viewtopic.php?f=48&t=18723

Best,

-- Rodney

**Comment by AndreyNikiforov** [comment]
Rodney,

All vault-specific interactions are in vault2gitLib/Processor.cs/vault*() methods. As you can see two main methods are used: one for getting history of changes and another for getting files. To make Fortress Client working, you'll have to figure out how you can get history and get then get files. SourceGear may have sample code.

Hope this helps.
~Andrey
