### ISSUE TITLE
Does this work with Vault v5?

### ISSUE THREAD

**Issue by jchannon** [AndreyNikiforov/vault2git#8]
You cannot believe how happy I am to have found this!!!

As the title suggests, does this work with Vault v5?

**Comment by AndreyNikiforov** [comment]
@jchannon vault2git was built against Vault 4 dlls. As far as I know every major upgrade of Vault (e.g 4.2 -> 4.3) required new dlls to work properly, and ver 5 introduced some API changes. You can try replacing ver 4 dlls with ones from ver 5 and check functionality. All vault interfaces are in vault2gitLib/Processor.cs/vault*() methods, so if you have to adjust code, then look here first.

**Comment by jchannon** [comment]
I'm about to try referencing the v5 DLL's but have noticed that v5 API does not contain SGDiff  DLL that you reference in vault2git

**Comment by AndreyNikiforov** [comment]
@jchannon if you look at folders in source tree, you'll notice that sgdiff is part of VaultClientLib. vault2git does not use it directly.

It may be better to extract Vault v5 client API into its own folder, remove all refs to v4 (including sgdiff.dll) from project, and add refs to v5.

**Comment by jchannon** [comment]
Thanks. Have it working but its very very slow getting information out of Vault.

**Comment by breiter** [comment]
It works with Vault 6. I just converted a large Vault 6 repository today.
